" disable vi compatibility (emulation of old bugs)
set nocompatible

" set leader keys
let mapleader = ','
let maplocalleader = ';'

" Use plugins config 
if filereadable(expand("~/.vimrc.plugins"))
  source ~/.vimrc.plugins
endif
" 

" System clipboard support
if has('clipboard')
  "if has('unnamedplus') " When possible use + register for copy-paste
  "set clipboard=unnamed,unnamedplus
  "else " On mac and Windows, use * register for copy-paste
  "set clipboard=unnamed
  "endif
endif

set background=dark

" set UTF-8 encoding
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8
" use indentation of previous line
set autoindent
" use intelligent indentation for C
set smartindent
" configure tabwidth and insert spaces instead of tabs
set tabstop=2        " tab width is 2 spaces
set shiftwidth=2     " indent also with 2 spaces
set expandtab        " expand tabs to spaces
" wrap lines at 120 chars. 80 is somewaht antiquated with nowadays displays.
"set textwidth=80
" this turns off physical line wrapping (ie: automatic insertion of newlines)
set textwidth=0 wrapmargin=0
set wrap linebreak nolist

" turn syntax highlighting on
set t_Co=256
syntax on
"color"
let g:hybrid_use_Xresources = 1
colorscheme hybrid
" turn line numbers on
" set number
" highlight matching braces
set showmatch
" intelligent comments
set comments=sl:/*,mb:\ *,elx:\ */
" Affiche la position du curseur 'ligne,colonne'
set ruler
" Affiche une barre de status en bas de l'écran
set laststatus=2
" Contenu de la barre de status
set statusline=%<%f%h%m%r%=%l,%c\ %P
" Autorise le passage d'une ligne à l'autre avec les flèches gauche et droite
set whichwrap=<,>,[,]

" Allow mouse use
set mouse=a


" Press F3 to toggle highlighting on/off, and show current value.
noremap <F3> :set hlsearch! hlsearch?<CR>
" switch between header/source with F4
map <F4> :e %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<CR>
" in normal mode F5 will save the file
nmap <F5> :w<CR>
" in insert mode F5 will exit insert, save, enters insert again
imap <F5> <ESC>:w<CR>i
" F3: Toggle list (display unprintable characters).

" Reload vimrc
map <F6> :so ~/.vimrc<CR>

"F7 reindents a whole file"
map <F7> mzgg=G`z

nnoremap <F9> :set list!<CR>
" Press F8 to toggle set number on/off, and show current value.
noremap <F8> :set number! relativenumber! number?<CR>

" Command history length
set history=1000
" Always keep a visible line above cursor
set scrolloff=1
" Affiche les commandes dans la barre de status
set showcmd

" Les recherches ne sont pas 'case sensitives'
set ignorecase
" Searching starts after you enter the string
set incsearch
" Turns on search highlighting
set hlsearch

" enable persistant undo history
set undofile
" set a directory to store the undo history
set undodir=~/.vimundo/

""Store swap files in fixed location, not current directory.
"set dir=~/.dotfiles/.vimswap//,/var/tmp//,/tmp//,.

set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
"set list "displays all invisible characters"

"Filetype detection for indent and highlighting
filetype plugin indent on

"Map NERDTree on current dir to <F12>
map <F12> :NERDTreeToggle<CR>

" vimrc de Ben
set wildmenu " Show list instead of just completing
set wildmode=list:longest,full " Command <Tab> completion, list matches, then longest common part, then all.
set completeopt+=menuone
set completeopt-=preview
" Default Vim completion should not look for all include files (slow)
set complete-=i
" Default Vim completion should not look for all tags (slow)
set complete-=t
" When the popup menu is opened, make the Enter key select the completion
" entry instead of creating a new line
set cursorline " Highlight current line
" Limit syntax highlighting with
"set synmaxcol=200
"Fast terminal
set ttyfast


"No auto fold on startup
set foldlevelstart=99

" System clipboard support
if has('clipboard')
  if has('unnamedplus') " When possible use + register for copy-paste
    set clipboard=unnamed,unnamedplus
  else " On mac and Windows, use * register for copy-paste
    set clipboard=unnamed
  endif
endif

" Fix mouse in vim under tmux
if &term =~ '^screen'
  " tmux knows the extended mouse mode
  set ttymouse=xterm2
endif

inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
" Disable Ex mode
nnoremap Q <nop>

map <C-K> :pyf /usr/share/vim/addons/syntax/clang-format-3.6.py<cr>
imap <C-K> <c-o>:pyf /usr/share/vim/addons/syntax/clang-format-3.6.py<cr>

